{% set name = "album-runner" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c2db56fa706ff69bffdf63ac6c008adf8325dd4ae6ad4d18931ee310c96391fd

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - album.runner
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://album.solutions
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: album is a tool for unifying computational tools across frameworks, languages, and environments
  doc_url: https://docs.album.solutions
  dev_url: https://gitlab.com/album-app/album-runner

extra:
  recipe-maintainers:
    - frauzufall
